# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fast_process?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&nullCatalogMeansCurrent=true
    username: gongmin
    password: gongmin
    driver-class-name: com.mysql.cj.jdbc.Driver
  # spring-security配置
  security:
    user:
      name: root
      password: root

# 日志级别配置
logging:
  level:
    root: debug
    com.gm: debug